#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

# curl with firefox cookies.sqlite
# usage: curlfire [profile | env.FF_PROFILE] URL
#   curlfire foo http://example.com
#   FF_PROFILE=foo curlfire http://example.com

profile=${1:-${FF_PROFILE:-default}}
curlcookies="$(mktemp /tmp/curlcookies.XXXXXXXXXX)"
cookiefire $profile >"$curlcookies"
curl -b "$curlcookies" "$@"
rm "$curlcookies"
