#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

profile=${1:-default}
curlcookies="$(mktemp /tmp/curlcookies.XXXXXXXXXX)"
cookiefire $profile >"$curlcookies"
curl -b "$curlcookies" "$@"
rm "$curlcookies"
#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

profile=${1:-${PROFILE:-jtm}}
curlcookies="$(mktemp /tmp/curlcookies.XXXXXXXXXX)"
cookiefire $profile >"$curlcookies"
curl -b "$curlcookies" "$@"
rm "$curlcookies"
